# Tooling configuration

[tool.isort]
line_length = 100
profile = "black"
multi_line_output = 3
force_single_line = true
add_imports=["from __future__ import annotations"]

[tool.black]
line-length = 100
target-version = ['py38']

[tool.pylint.main]
    [tool.pylint.messages_control]
    max-line-length = 100
    disable=[
        "logging-fstring-interpolation",
        "too-many-instance-attributes",
        "unnecessary-pass",
        "unnecessary-ellipsis",
        "too-many-arguments"
    ]
